apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld-two
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld-two
  template:
    metadata:
      labels:
        app: aks-helloworld-two
    spec:
      containers:
      - name: aks-helloworld-two
        image: dsopublic.azurecr.io/launch-demo-java-hex-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: TITLE
          value: "AKS Ingress Demo"
      imagePullSecrets:
      - name: docker-secret
