apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
  namespace: cert-manager
spec:
  secretName: demo-cert-tls # pragma: allowlist secret
  issuerRef:
    name: letsencrypt-cluster
    kind: ClusterIssuer
  dnsNames:
    - demo-tls.sandbox.launch.nttdata.com
